# The scheduler can assign the Pod to any node within Zone V, as long as there is atleast one Pod within Zone V already labeled 
# with env=prod and there is no Pod within Zone V already labeled with tier=stg and preferably the Pods doesn't have labeled with tier=srv within Zone V.
# condtions explaination: (env=prod --> zone A) AND (tier!=stg  --> zone A) OR (tier!=srv --> zone A)
apiVersion: v1
kind: Pod
metadata:
  name: podaffinity8
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: env
            operator: In
            values:
            - prod
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - stg
        topologyKey: topology.kubernetes.io/zone
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: tier
              operator: In
              values:
              - srv
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
