apiVersion: v1
kind: Pod
metadata:
  name: podaffinity1
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: env
            operator: In
            values:
            - prod
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
