# The scheduler can assign the Pod to any node within Zone V, as long as there is no Pod within Zone V already labeled 
#with tier=stg and the pods labeled with env=dev.
apiVersion: v1
kind: Pod
metadata:
  name: podaffinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: env
            operator: In
            values:
            - dev
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - stg
        topologyKey: topology.kubernetes.io/zone     
  containers:
  - name: nginx
    image: nginx
