# The scheduler can assign the Pod to any node within Zone V, as long as there is atleast one Pod within Zone V already labeled 
# with env=dev and preferably the Pods doesn't have labeled with tier=stg within Zone V.
# conditon: (env=dev --> zone A[must satify) OR (tier!=stg --> zone A) 
apiVersion: v1
kind: Pod
metadata:
  name: podaffinity5
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: env
            operator: In
            values:
            - dev
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: tier
              operator: In
              values:
              - stg
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
